const router = require('express').Router()
const { authMiddleware, adminOnly } = require('../middlewares/auth')
const { listar, buscarPorId, criar, atualizar, excluir } = require('../controllers/protocoloController')
router.use(authMiddleware)
router.get('/', listar)
router.get('/:id', buscarPorId)
router.post('/', criar)
router.patch('/:id', atualizar)
router.delete('/:id', adminOnly, excluir)
module.exports = router
